arm_test:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: arm_test
    joint_speed: 0.4
    motor:
        id: 2
        init: 2351
        min: 1100
        max: 3500
