left_motor:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_motor
    joint_speed: 0.4
    motor:
        id: 1
        init: 0
        min: 0
        max: 3396

right_motor:
    controller:
        package: dynamixel_controllers
        module: joint_torque_controller
        type: JointTorqueController
    joint_name: right_motor
    joint_speed: 0.4
    motor:
        id: 2
        init: 0
        min: 0
        max: 3396

pan_kinect:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_kinect
    joint_speed: 0.4
    motor:
        id: 10
        init: 1370
        min: 346
        max: 2394

tilt_kinect:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: tilt_kinect
    joint_speed: 0.4
    motor:
        id: 11
        init: 1775
        min: 1217
        max: 1992

tilt_laser:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: tilt_laser
    joint_speed: 1.0
    motor:
        id: 1
        init: 214
        min: 20
        max: 856
        
mark44_1:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: mark44_1
    joint_speed: 0.4
    motor:
        id: 211
        init: 32748
        min: 1000
        max: 64500

right_1:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_1
    joint_speed: 0.4
    motor:
        id: 20
        init: 22591
        min: 16383
        max: 23665

right_2:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_2
    joint_speed: 0.4
    motor:
        id: 21        
        init: 26495
        min: 11313
        max: 41677

right_3:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_3
    joint_speed: 0.7
    motor:
        id: 22
        init: 623
        min: 0
        max: 1024

prismatic:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: prismatic
    joint_speed: 0.4
    motor:
        id: 50
        init: 0
        min: 960
        max: 2050

joint1:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint1
    joint_speed: 0.4
    joint_torque_imit : 1.00
    motor:
        id: 40
        init: 1949
        min: 892
        max: 2243         

joint2:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint2
    joint_speed: 0.4
    joint_torque_limit : 1.00
    motor:
        id: 41
        init: 513
        min: 441
        max: 771

joint3:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint3
    joint_speed: 0.4 
    joint_torque_limit : 1.00
    motor:
        id: 42
        init: 1789
        min: 674
        max: 2873
                
gripper:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: gripper
    joint_speed: 2.0
    joint_torque_limit : 1.0
    motor:
        id: 43
        init: 943
        min: 700
        max: 1683
