pan_kinect:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_kinect
    joint_speed: 0.4
    motor:
        id: 10
        init: 2355
        min: 1374
        max: 3396

tilt_kinect:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: tilt_kinect
    joint_speed: 0.4
    motor:
        id: 11
        init: 2000
        min: 1563
        max: 2015

pan_kinect_2:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_kinect_2
    joint_speed: 0.4
    motor:
        id: 10
        init: 2552
        min: 1469
        max: 3300

tilt_kinect_2:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: tilt_kinect_2
    joint_speed: 0.4
    motor:
        id: 11
        init: 2015
        min: 1570
        max: 2030

tilt_laser:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: tilt_laser
    joint_speed: 1.0
    motor:
        id: 1
        init: 214
        min: 20
        max: 856
        
mark44_1:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: mark44_1
    joint_speed: 0.4
    motor:
        id: 21
        init: 32748
        min: 1000
        max: 64500

mark44_2:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: mark44_2
    joint_speed: 0.4
    motor:
        id: 22
        init: 32771
        min: 1000
        max: 64500

mark44_3:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: mark44_3
    joint_speed: 0.4
    motor:
        id: 23
        init: 65300
        min: 26130
        max: 54612

mark43_pris:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: mark43_pris
    joint_speed: 0.4
    motor:
        id: 26
        init: 1336
        min: 1336
        max: 7515

joint1:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint1
    joint_speed: 0.4
    motor:
        id: 40
        init: 2048
        min: 0
        max: 4095          
        
joint3:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint3
    joint_speed: 0.4
    motor:
        id: 42
        init: 2048
        min: 0
        max: 4095
        
joint2:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint2
    joint_speed: 0.4
    motor:
        id: 41
        init: 403
        min: 65
        max: 420
                
gripper:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: gripper
    joint_speed: 0.4
    joint_torque_limit : 0.30
    motor:
        id: 43
        init: 800
        min: 620
        max: 1283
