left_motor:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_motor
    joint_speed: 0.4
    motor:
        id: 1
        init: 0
        min: 0
        max: 3396

right_motor:
    controller:
        package: dynamixel_controllers
        module: joint_torque_controller
        type: JointTorqueController
    joint_name: right_motor
    joint_speed: 0.4
    motor:
        id: 2
        init: 0
        min: 0
        max: 3396

pan_kinect:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_kinect
    joint_speed: 0.4
    motor:
        id: 10
        init: 2030
        min: 1005
        max: 3045

tilt_kinect:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: tilt_kinect
    joint_speed: 0.4
    motor:
        id: 11
        init: 1775
        min: 1217
        max: 1992

tilt_laser:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: tilt_laser
    joint_speed: 1.0
    motor:
        id: 1
        init: 214
        min: 20
        max: 856
        
mark44_1:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: mark44_1
    joint_speed: 0.4
    motor:
        id: 211
        init: 32748
        min: 1000
        max: 64500

shoulder_L_20:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: shoulder_L_20
    joint_speed: 0.4
    motor:
        id: 20
        init: 586
        min: 0
        max: 1024

shoulder_L_21:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: shoulder_L_21
    joint_speed: 0.4
    motor:
        id: 21
        init: 525
        min: 0
        max: 1024

elbow_L_22:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: elbow_L_22
    joint_speed: 0.4
    motor:
        id: 22
        init: 705
        min: 0
        max: 728

mark44_2:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: mark44_2
    joint_speed: 0.4
    motor:
        id: 22
        init: 32771
        min: 1000
        max: 64500

mark44_3:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: mark44_3
    joint_speed: 0.7
    motor:
        id: 23
        init: 32399
        min: 14349
        max: 54449

prismatic:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: prismatic
    joint_speed: 0.4
    motor:
        id: 50
        init: 0
        min: 960
        max: 2050

hand_L_40:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: hand_L_40
    joint_speed: 0.4
    joint_torque_limit : 1.00
    motor:
        id: 40
        init: 2047
        min: 0
        max: 4095         
        
hand_L_41:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: hand_L_41
    joint_speed: 0.4
    joint_torque_limit : 1.00
    motor:
        id: 41
        init: 2047
        min: 0
        max: 4095
        
hand_L_42:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: hand_L_42
    joint_speed: 0.4
    joint_torque_limit : 1.00
    motor:
        id: 42
        init: 2047
        min: 0
        max: 4095
                
gripper_L_43:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: griper_L_43
    joint_speed: 0.4
    joint_torque_limit : 0.60
    motor:
        id: 43
        init: 800
        min: 500
        max: 1283

hand_R_45:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: hand_R_45
    joint_speed: 0.4
    joint_torque_limit : 1.00
    motor:
        id: 45
        init: 2047
        min: 0
        max: 4095        
        
hand_R_46:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: hand_R_46
    joint_speed: 0.4
    joint_torque_limit : 1.00
    motor:
        id: 46
        init: 512
        min: 0
        max: 1024
        
hand_R_47:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: hand_R_47
    joint_speed: 0.4
    joint_torque_limit : 1.00
    motor:
        id: 47
        init: 2047
        min: 0
        max: 4095
                
gripper_R_48:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: griper_R_48
    joint_speed: 0.4
    joint_torque_limit : 0.60
    motor:
        id: 48
        init: 800
        min: 500
        max: 1283
