left_shoulder_1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_shoulder_1_joint
    joint_speed: 0.4
    motor:
        id: 25
        init: 51519
        min: 12000
        max: 58500

left_shoulder_2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_shoulder_2_joint
    joint_speed: 0.4
    motor:
        id: 26
        init: 30463
        min: 10000
        max: 45000

left_elbow_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_elbow_joint
    joint_speed: 0.4
    motor:
        id: 27
        init: 40200
        min: 25150
        max: 43270

left_wrist_1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_wrist_1_joint
    joint_speed: 0.4
    joint_torque_limit : 1.00
    motor:
        id: 45
        init: 968
        min: 630
        max: 3000         

left_wrist_2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_wrist_2_joint
    joint_speed: 0.4
    joint_torque_limit : 1.00
    motor:
        id: 46
        init: 2255
        min: 1750
        max: 3300

left_wrist_3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_wrist_3_joint
    joint_speed: 0.4 
    joint_torque_limit : 1.00
    motor:
        id: 47
        init: 1800
        min: 770
        max: 3000

left_gripper_joint_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_gripper_joint
    joint_speed: 0.4
    joint_torque_limit : 0.2
    motor:
        id: 48
        init: 684
        min: 665
        max: 985 
