left_shoulder_1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_shoulder_1_joint
    joint_speed: 15
    motor:
        id: 35
        init: 250
        min: 56
        max: 1306

left_shoulder_2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_shoulder_2_joint
    joint_speed: 15
    motor:
        id: 36
        init: 2036
        min: 1022
        max: 3068

left_elbow_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_elbow_joint
    joint_speed: 15
    motor:
        id: 37
        init: 898
        min: 625
        max: 1931

left_wrist_1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_wrist_1_joint
    joint_speed: 0.4
    joint_torque_limit : 1.00
    motor:
        id: 45
        init: 1106
        min: 0
        max: 4095         

left_wrist_2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_wrist_2_joint
    joint_speed: 0.4
    joint_torque_limit : 1.00
    motor:
        id: 46
        init: 2034
        min: 0
        max: 4095

left_wrist_3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_wrist_3_joint
    joint_speed: 0.4 
    joint_torque_limit : 1.00
    motor:
        id: 47
        init: 999
        min: 0
        max: 4095

left_gripper_joint_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_gripper_joint
    joint_speed: 0.4
    joint_torque_limit : 0.3
    motor:
        id: 48
        init: 699
        min: 0
        max: 1023
