pan_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint
    joint_speed: 0.4
    motor:
        id: 10
        init: 1370
        min: 346
        max: 2394

tilt_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: tilt_joint
    joint_speed: 0.4
    motor:
        id: 11
        init: 1775
        min: 1217
        max: 1992
