pan_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint
    joint_speed: 0.4
    motor:
        id: 10
        init: 2842
        min: 2100
        max: 3400

tilt_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: tilt_joint
    joint_speed: 0.4
    motor:
        id: 11
        init: 1750
        min: 1300
        max: 1900
