pan_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint
    joint_speed: 0.7
    motor:
        id: 10
        init: 2435
        min: 1531
        max: 3410

tilt_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: tilt_joint
    joint_speed: 0.4
    motor:
        id: 11
        init: 1800
        min: 1259
        max: 2008