prismatic_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: torso_joint
    joint_speed: 0.4
    motor:
        id: 50
        init: 0
        min: 960
        max: 2050
