right_shoulder_1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_shoulder_1_joint
    joint_speed: 0.4
    motor:
        id: 20
        init: 19071
        min: 0
        max: 65535

right_shoulder_2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_shoulder_2_joint
    joint_speed: 0.4
    motor:
        id: 21
        init: 35000
        min: 0
        max: 65535

right_elbow_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_elbow_joint
    joint_speed: 0.4
    motor:
        id: 22
        init: 40895
        min: 0
        max: 65535

right_wrist_1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_wrist_1_joint
    joint_speed: 0.4
    joint_torque_limit : 1.00
    motor:
        id: 40
        init: 1949
        min: 892
        max: 2243         

right_wrist_2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_wrist_2_joint
    joint_speed: 0.4
    joint_torque_limit : 1.00
    motor:
        id: 41
        init: 513
        min: 441
        max: 771

right_wrist_3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_wrist_3_joint
    joint_speed: 0.4 
    joint_torque_limit : 1.00
    motor:
        id: 42
        init: 1789
        min: 674
        max: 2873
                
right_gripper_joint_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_gripper_joint
    joint_speed: 2.0
    joint_torque_limit : 1.0
    motor:
        id: 43
        init: 943
        min: 700
        max: 1683
