right_shoulder_1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_shoulder_1_joint
    joint_speed: 0.4
    motor:
        id: 20
        init: 19775
        min: 8000
        max: 60600

right_shoulder_2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_shoulder_2_joint
    joint_speed: 0.4
    motor:
        id: 21
        init: 35775
        min: 26000
        max: 53000

right_elbow_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_elbow_joint
    joint_speed: 0.4
    motor:
        id: 22
        init: 25343
        min: 21900
        max: 37250

right_wrist_1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_wrist_1_joint
    joint_speed: 0.4
    joint_torque_limit : 2.00
    motor:
        id: 40
        init: 2233
        min: 200
        max: 3900        

right_wrist_2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_wrist_2_joint
    joint_speed: 0.4
    joint_torque_limit : 2.00
    motor:
        id: 41
        init: 2016
        min: 1500
        max: 3000

right_wrist_3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_wrist_3_joint
    joint_speed: 0.4 
    joint_torque_limit : 2.00
    motor:
        id: 42
        init: 1825
        min: 100
        max: 3900

right_gripper_joint_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_gripper_joint
    joint_speed: 0.6
    joint_torque_limit : 0.5
    motor:
        id: 43
        init: 1230
        min: 700
        max: 1600
