right_shoulder_1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_shoulder_1_joint
    joint_speed: 0.4
    motor:
        id: 20
        init: 8895
        min: 11583
        max: 21000

right_shoulder_2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_shoulder_2_joint
    joint_speed: 0.4
    motor:
        id: 21
        init: 38015
        min: 25215
        max: 47295

right_elbow_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_elbow_joint
    joint_speed: 0.4
    motor:
        id: 22
        init: 21439
        min: 21439
        max: 40383

right_wrist_1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_wrist_1_joint
    joint_speed: 0.4
    joint_torque_limit : 1.00
    motor:
        id: 40
        init: 1015
        min: 500
        max: 3000         

right_wrist_2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_wrist_2_joint
    joint_speed: 0.4
    joint_torque_limit : 1.00
    motor:
        id: 41
        init: 490
        min: 420
        max: 830

right_wrist_3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_wrist_3_joint
    joint_speed: 0.4 
    joint_torque_limit : 1.00
    motor:
        id: 42
        init: 1733
        min: 600
        max: 3000
                
right_gripper_joint_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_gripper_joint
    joint_speed: 2.0
    joint_torque_limit : 1.0
    motor:
        id: 43
        init: 943
        min: 700
        max: 1683
