right_shoulder_1_controller:
    controller:
        package: hardware_bridge
        module: joint_position_controller_with_ratio
        type: JointPositionWithRatioController
    joint_name: right_shoulder_1_joint
    joint_speed: 0.4
    mechanical_ratio: 1.75
    motor:
        id: 20
        init: 19775
        min: 14550
        max: 23850

right_shoulder_2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_shoulder_2_joint
    joint_speed: 0.4
    motor:
        id: 21
        init: 38720
        min: 22600
        max: 54200

right_elbow_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_elbow_joint
    joint_speed: 0.4
    motor:
        id: 22
        init: 40191
        min: 21760
        max: 41300

right_wrist_1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_wrist_1_joint
    joint_speed: 0.4
    joint_torque_limit : 1.00
    motor:
        id: 40
        init: 1015
        min: 630
        max: 3000         

right_wrist_2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_wrist_2_joint
    joint_speed: 0.4
    joint_torque_limit : 1.00
    motor:
        id: 41
        init: 521
        min: 425
        max: 830

right_wrist_3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_wrist_3_joint
    joint_speed: 0.4 
    joint_torque_limit : 1.00
    motor:
        id: 42
        init: 1817
        min: 770
        max: 3000
                
right_gripper_joint_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_gripper_joint
    joint_speed: 2.0
    joint_torque_limit : 1.0
    motor:
        id: 43
        init: 720
        min: 545
        max: 720
