right_shoulder_1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_shoulder_1_joint
    joint_speed: 0.4
    motor:
        id: 20
        init: 46720
        min: 6200
        max: 60600

right_shoulder_2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_shoulder_2_joint
    joint_speed: 0.4
    motor:
        id: 21
        init: 29440
        min: 13120
        max: 40000

right_elbow_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_elbow_joint
    joint_speed: 0.4
    motor:
        id: 22
        init: 39871
        min: 27970
        max: 43380

right_wrist_1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_wrist_1_joint
    joint_speed: 0.4
    joint_torque_limit : 4.00
    motor:
        id: 40
        init: 2233
        min: 200
        max: 3900        

right_wrist_2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_wrist_2_joint
    joint_speed: 0.4
    joint_torque_limit : 4.00
    motor:
        id: 41
        init: 2240
        min: 1769
        max: 3536

right_wrist_3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_wrist_3_joint
    joint_speed: 0.4 
    joint_torque_limit : 4.00
    motor:
        id: 42
        init: 1800
        min: 307
        max: 3900

right_gripper_joint_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_gripper_joint
    joint_speed: 0.6
    joint_torque_limit : 1.0
    motor:
        id: 43
        init: 751
        min: 751
        max: 1360
