right_shoulder_1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_shoulder_1_joint
    joint_speed: 0.2
    motor:
        id: 30
        init: 52100
        min: 3600
        max: 58300

right_shoulder_2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_shoulder_2_joint
    joint_speed: 0.2
    motor:
        id: 31
        init: 59455
        min: 40050
        max: 62000

right_elbow_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_elbow_joint
    joint_speed: 0.2
    motor:
        id: 32
        init: 41023
        min: 24600
        max: 43700

right_wrist_1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_wrist_1_joint
    joint_speed: 0.4
    joint_torque_limit : 1.0
    motor:
        id: 40
        init: 473
        min: 100
        max: 900

right_wrist_2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_wrist_2_joint
    joint_speed: 0.2
    joint_torque_limit : 0.9
    motor:
        id: 41
        init: 2221
        min: 1769
        max: 3536

right_wrist_3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_wrist_3_joint
    joint_speed: 0.4 
    joint_torque_limit : 1.00
    motor:
        id: 42
        init: 2624
        min: 900
        max: 3750

right_gripper_joint_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_gripper_joint
    joint_speed: 0.6
    joint_torque_limit : 0.8
    motor:
        id: 43
        init: 882
        min: 200
        max: 1500
